services:
  mcp_clickhouse:
    build:
      context: .
    container_name: mcp_clickhouse
    restart: unless-stopped
    ports:
      - '9008:8000'
    environment:
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-127.0.0.1}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8123}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-password}
      - CLICKHOUSE_SECURE=true
      - CLICKHOUSE_VERIFY=true
      - CLICKHOUSE_CONNECT_TIMEOUT=30
      - CLICKHOUSE_SEND_RECEIVE_TIMEOUT=30
      - CLICKHOUSE_MCP_SERVER_TRANSPORT=sse
      - CLICKHOUSE_MCP_BIND_HOST=0.0.0.0
      - CLICKHOUSE_MCP_BIND_PORT=8000
    command: python -m mcp_clickhouse.main
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8000/health'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'
